In [1]:
import pandas as pd
import numpy as np

In [2]:
data=pd.read_csv("data_science_project.csv")

In [3]:
data.head()

,Fund Number,Market Cap,Type,Risk,Assets,Turnover Ratio(%),SD,Sharpe Ratio,1YrReturn%,3YrReturn%,5YrReturn%,10YrReturn%,Expense Ratio,Star Rating
0,RF001,Large,Growth,Average,654.66,57.0,10.90,1.59,9.20,18.20,15.92,9.53,1.11,Five
1,RF002,Large,Growth,Low,1999.02,0.0,9.44,1.32,13.31,12.75,12.27,9.70,1.10,Four
2,RF003,Large,Growth,Average,97.70,29.0,10.50,1.28,8.18,13.79,13.83,6.93,1.27,Three
3,RF004,Large,Growth,Average,1079.96,58.0,11.04,1.32,11.85,15.00,15.50,11.35,1.00,Four
4,RF005,Large,Growth,Average,9861.25,103.0,9.88,1.45,13.07,14.81,14.59,8.20,0.97,Three

Present which stock has highest risk and return

In [10]:
high_risk=data[data["Risk"]=="High"]

In [11]:
high_risk["Fund Number"]

49     RF050
83     RF084
84     RF085
85     RF086
103    RF104
       ...
399    RF400
400    RF401
401    RF402
403    RF404
406    RF407
Name: Fund Number, Length: 70, dtype: object

In [14]:
data["1YrReturn%"].max()

21.7

In [16]:
data[data["1YrReturn%"]==21.7]

,Fund Number,Market Cap,Type,Risk,Assets,Turnover Ratio(%),SD,Sharpe Ratio,1YrReturn%,3YrReturn%,5YrReturn%,10YrReturn%,Expense Ratio,Star Rating
55,RF056,Large,Growth,Average,1153.55,76.0,10.82,1.8,21.7,20.68,19.65,9.94,0.87,Five

In [18]:
data["3YrReturn%"].max()

30.89

In [19]:
data[data["3YrReturn%"]==30.89]

,Fund Number,Market Cap,Type,Risk,Assets,Turnover Ratio(%),SD,Sharpe Ratio,1YrReturn%,3YrReturn%,5YrReturn%,10YrReturn%,Expense Ratio,Star Rating
315,RF316,Mid-Cap,Value,Average,2075.38,17.0,10.57,1.72,6.71,30.89,14.2,4.54,1.56,Three

In [20]:
data["5YrReturn%"].max()

22.83

In [21]:
data[data["3YrReturn%"]==22.83]

Empty DataFrame
Columns: [Fund Number, Market Cap, Type, Risk, Assets, Turnover Ratio(%), SD, Sharpe Ratio, 1YrReturn%, 3YrReturn%, 5YrReturn%, 10YrReturn%, Expense Ratio, Star Rating]
Index: []

In [22]:
data["10YrReturn%"].max()

17.11

In [23]:
data[data["3YrReturn%"]==17.11]

Empty DataFrame
Columns: [Fund Number, Market Cap, Type, Risk, Assets, Turnover Ratio(%), SD, Sharpe Ratio, 1YrReturn%, 3YrReturn%, 5YrReturn%, 10YrReturn%, Expense Ratio, Star Rating]
Index: []

In [ ]:
# Stock wise groth on year to year basis

In [25]:
data["Risk"].unique()

array(['Average', 'Low', 'High'], dtype=object)

In [27]:
data[data["Risk"]=="Average"]

,Fund Number,Market Cap,Type,Risk,Assets,Turnover Ratio(%),SD,Sharpe Ratio,1YrReturn%,3YrReturn%,5YrReturn%,10YrReturn%,Expense Ratio,Star Rating
0,RF001,Large,Growth,Average,654.66,57.0,10.90,1.59,9.20,18.20,15.92,9.53,1.11,Five
2,RF003,Large,Growth,Average,97.70,29.0,10.50,1.28,8.18,13.79,13.83,6.93,1.27,Three
3,RF004,Large,Growth,Average,1079.96,58.0,11.04,1.32,11.85,15.00,15.50,11.35,1.00,Four
4,RF005,Large,Growth,Average,9861.25,103.0,9.88,1.45,13.07,14.81,14.59,8.20,0.97,Three
5,RF006,Large,Growth,Average,2355.65,25.0,10.65,1.41,14.66,15.58,15.00,6.80,1.00,Three
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
396,RF397,Small,Value,Average,325.74,68.0,11.76,1.20,2.52,14.34,14.45,5.36,1.41,Two
397,RF398,Small,Value,Average,75.01,0.0,12.08,1.07,4.41,10.88,11.01,6.66,1.27,Three
402,RF403,Small,Value,Average,460.63,40.0,11.55,1.08,3.69,12.54,11.46,5.60,1.37,Two
404,RF405,Small,Value,Average,1862.39,44.0,11.56,1.34,3.15,15.97,17.33,8.79,1.57,Three
405,RF406,Small,Value,Average,1172.08,121.0,12.83,1.23,9.79,16.17,16.38,8.91,1.51,Four

In [28]:
data[data["Risk"]=="Low"]

,Fund Number,Market Cap,Type,Risk,Assets,Turnover Ratio(%),SD,Sharpe Ratio,1YrReturn%,3YrReturn%,5YrReturn%,10YrReturn%,Expense Ratio,Star Rating
1,RF002,Large,Growth,Low,1999.02,0.00,9.44,1.32,13.31,12.75,12.27,9.70,1.10,Four
9,RF010,Large,Growth,Low,3503.40,47.31,9.03,1.47,8.36,13.75,12.00,7.53,1.05,Three
17,RF018,Large,Growth,Low,105.29,6.29,9.39,1.35,9.58,13.03,12.90,6.56,0.96,Two
41,RF042,Large,Growth,Low,1732.57,124.00,9.20,1.50,10.17,14.29,12.01,6.61,0.78,Two
59,RF060,Large,Growth,Low,3889.00,12.00,8.97,1.53,12.14,14.25,13.54,8.05,1.18,Two
61,RF062,Large,Growth,Low,118.21,32.00,9.42,1.07,12.94,16.45,13.73,6.41,1.25,Three
66,RF067,Large,Growth,Low,724.40,59.00,9.42,1.85,15.02,18.48,17.20,8.19,0.89,Four
70,RF071,Large,Growth,Low,5275.93,14.10,9.40,1.61,12.52,15.81,13.29,7.27,0.89,Three
75,RF076,Large,Growth,Low,143.21,52.00,8.90,1.64,10.85,15.25,12.30,6.05,0.95,Two
98,RF099,Large,Growth,Low,30.96,7.49,9.17,1.65,14.20,15.85,14.54,6.38,1.78,Three
100,RF101,Large,Growth,Low,124.67,14.00,9.35,1.30,5.21,12.40,10.43,7.56,0.93,Three
111,RF112,Large,Growth,Low,43.83,23.00,9.04,1.68,12.26,15.93,13.39,7.96,0.94,Three
116,RF117,Large,Growth,Low,216.46,8.00,9.32,1.67,15.21,16.26,14.86,7.27,1.15,Three
134,RF135,Large,Value,Low,8934.63,57.00,7.00,1.78,13.72,13.03,12.23,7.01,0.93,Four
136,RF137,Large,Value,Low,3375.78,36.50,9.45,1.66,12.53,16.39,13.82,6.96,0.98,Four
139,RF140,Large,Value,Low,284.13,9.00,8.45,1.32,9.39,11.38,10.65,6.83,1.25,Three
142,RF143,Large,Value,Low,27291.98,6.00,8.72,1.38,8.77,12.32,12.52,8.10,0.95,Three
148,RF149,Large,Value,Low,5939.24,32.00,8.01,1.80,12.94,15.12,13.98,7.00,1.18,Three
150,RF151,Large,Value,Low,234.20,18.00,9.10,1.72,11.35,16.42,15.67,6.95,0.66,Four
151,RF152,Large,Value,Low,2316.74,6.00,7.98,1.62,12.52,13.45,13.05,6.97,1.01,Three
153,RF154,Large,Value,Low,252.32,20.36,9.35,1.41,16.44,13.61,11.37,6.13,0.99,Three
155,RF156,Large,Value,Low,3874.82,49.00,9.20,1.67,11.54,16.12,11.94,6.82,0.99,Three
156,RF157,Large,Value,Low,610.12,19.00,9.32,1.68,11.57,10.37,12.26,6.82,1.24,Three
162,RF163,Large,Value,Low,5383.37,52.00,8.94,1.68,12.85,15.75,12.75,5.39,0.63,Three
163,RF164,Large,Value,Low,8959.28,33.00,8.98,1.59,8.53,14.86,12.18,5.53,0.66,Two
164,RF165,Large,Value,Low,820.18,72.00,9.43,1.72,12.54,17.09,13.67,5.76,0.72,Three
171,RF172,Large,Value,Low,148.12,34.00,9.15,1.47,9.16,13.95,13.12,6.42,1.22,Three
173,RF174,Large,Value,Low,77.22,23.00,6.40,1.40,6.38,9.18,11.01,5.29,1.27,Two
176,RF177,Large,Value,Low,9066.93,30.00,9.10,1.73,14.28,16.49,16.17,8.37,1.04,Four
179,RF180,Large,Value,Low,20.37,29.00,8.73,1.57,9.58,14.26,10.96,6.61,0.95,Three
182,RF183,Large,Value,Low,314.82,14.34,8.24,1.54,11.49,13.14,12.66,8.04,1.00,Three
188,RF189,Large,Value,Low,488.47,51.00,8.27,1.68,14.49,14.48,15.17,5.96,0.80,Four
190,RF191,Large,Value,Low,11.85,14.00,8.65,0.77,1.23,6.59,7.13,3.61,1.92,Two
191,RF192,Large,Value,Low,5533.06,14.50,9.05,1.54,13.27,14.54,14.33,7.46,0.93,Three
196,RF197,Large,Value,Low,36.86,4.00,8.64,1.61,10.52,14.50,12.31,6.15,0.96,Three
203,RF204,Large,Value,Low,8.66,31.00,9.00,1.25,7.25,11.50,10.96,5.68,2.00,Two
246,RF247,Mid-Cap,Growth,Low,1546.93,18.00,8.92,1.73,11.27,18.10,17.72,10.33,1.44,Five
247,RF248,Mid-Cap,Growth,Low,3966.77,17.00,9.09,1.77,13.07,18.91,16.99,10.47,0.92,Four
288,RF289,Mid-Cap,Growth,Low,1130.73,45.00,9.31,1.48,8.67,14.26,10.94,5.03,1.59,One
303,RF304,Mid-Cap,Value,Low,1130.73,45.00,9.31,1.48,8.67,14.26,10.94,5.03,1.59,One
328,RF329,Mid-Cap,Value,Low,56.82,51.00,9.31,1.64,12.89,15.97,14.58,7.07,1.24,Three

In [29]:
data[data["Risk"]=="High"]

,Fund Number,Market Cap,Type,Risk,Assets,Turnover Ratio(%),SD,Sharpe Ratio,1YrReturn%,3YrReturn%,5YrReturn%,10YrReturn%,Expense Ratio,Star Rating
49,RF050,Large,Growth,High,12260.32,106.0,14.07,1.42,14.70,20.80,19.36,12.14,0.77,Five
83,RF084,Large,Growth,High,3412.00,31.0,13.62,1.35,6.42,19.02,18.05,10.26,0.96,Four
84,RF085,Large,Growth,High,226.62,21.0,13.17,1.19,5.65,15.95,15.44,9.71,1.22,Two
85,RF086,Large,Growth,High,367.38,39.0,14.51,1.17,2.90,17.23,17.02,11.13,1.27,Three
103,RF104,Large,Growth,High,4129.36,146.0,13.05,1.23,8.73,16.39,12.80,8.11,0.98,Two
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
399,RF400,Small,Value,High,802.03,51.0,13.36,0.57,-0.46,6.99,6.67,7.91,1.48,Two
400,RF401,Small,Value,High,19.29,506.0,13.18,1.01,4.03,13.29,11.94,6.08,1.56,Two
401,RF402,Small,Value,High,20.01,658.0,15.36,0.80,-2.70,12.47,11.15,4.15,1.53,One
403,RF404,Small,Value,High,97.16,32.0,13.57,0.86,0.84,11.36,13.67,9.02,1.35,Three
406,RF407,Small,Value,High,29.01,60.0,13.54,1.25,6.96,17.36,14.87,7.42,1.50,Three